# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "lens-customize-new"
client_id = "0cf5509b28e86796ecca10bee721a843"
application_url = "https://face-everybody-blank-springs.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://face-everybody-blank-springs.trycloudflare.com/auth/callback",
  "https://face-everybody-blank-springs.trycloudflare.com/auth/shopify/callback",
  "https://face-everybody-blank-springs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tbpts1.myshopify.com"
