# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "lens_custom_app"
client_id = "ef9dd2c156ad83e7425efc526dd5dd05"
application_url = "https://sick-determines-ethiopia-ahead.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_draft_orders"

[auth]
redirect_urls = [
  "https://specialized-mem-should-english.trycloudflare.com/auth/callback",
  "https://specialized-mem-should-english.trycloudflare.com/auth/shopify/callback",
  "https://specialized-mem-should-english.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "tbpts1.myshopify.com"
include_config_on_deploy = true
