# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef9dd2c156ad83e7425efc526dd5dd05"
name = "lenscustomapp"
handle = "lenscustomapp"
application_url = "https://lens-customizer.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_draft_orders,write_products"

[auth]
redirect_urls = ["https://lens-customizer.onrender.com/auth/callback", "https://lens-customizer.onrender.com/auth/shopify/callback", "https://lens-customizer.onrender.com/api/auth/callback"]

[pos]
embedded = false
